In [7]:
import scipy.stats as stats
import pandas as pd
import numpy as np

In [36]:
feRawData = pd.read_csv('./Files/2014_FEGuide.csv')
feRawData.head()

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Trans as listed in FE Guide (derived from col AA thru AF),City FE (Guide) - Conventional Fuel,...,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Rounded Adjusted (as shown on FE Label),CO2-PHEV Composite Rounded Adjusted Combined CO2,240V Charge Time at 240 volts (hours),120V Charge time at 120 Volts (hours),PHEV Total Driving Range (rounded to nearest 10 miles)DISTANCE,City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2014.0,aston martin,Aston Martin Lagonda Ltd,V8 Vantage,ASX,2,4.7,8,Auto(AM7),14,...,654,426,551,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014.0,aston martin,Aston Martin Lagonda Ltd,V8 Vantage,ASX,1,4.7,8,Manual(M6),13,...,680,461,581,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014.0,aston martin,Aston Martin Lagonda Ltd,V8 Vantage S,ASX,4,4.7,8,Auto(AM7),14,...,654,426,551,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014.0,aston martin,Aston Martin Lagonda Ltd,V8 Vantage S,ASX,3,4.7,8,Manual(M6),13,...,680,461,581,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014.0,Audi,Audi,R8,ADX,5,4.2,8,Auto(AM-S7),14,...,656,394,538,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
transType=feRawData['Trans as listed in FE Guide (derived from col AA thru AF)']

In [15]:
transType.head()

0      Auto(AM7)
1     Manual(M6)
2      Auto(AM7)
3     Manual(M6)
4    Auto(AM-S7)
Name: Trans as listed in FE Guide (derived from col AA thru AF), dtype: object

In [35]:
transTypeSeries = transType.str.split('(').str.get(0)
transTypeSeries.head()

0      Auto
1    Manual
2      Auto
3    Manual
4      Auto
Name: Trans as listed in FE Guide (derived from col AA thru AF), dtype: object

In [66]:
FeData = pd.DataFrame( [transTypeSeries, feRawData['City FE (Guide) - Conventional Fuel']]).T
FeData.rename( inplace=True,columns={'City FE (Guide) - Conventional Fuel':'MPG',
                      'Trans as listed in FE Guide (derived from col AA thru AF)':'TransType'})

FeData.head()

  TransType MPG
0      Auto  14
1    Manual  13
2      Auto  14
3    Manual  13
4      Auto  14